task :simple_compile do
  # Pick the right class path, depending if we're using an rvm installed JRuby
  jruby_cpath = ENV['MY_RUBY_HOME'] || ENV['JRUBY_HOME']
  raise 'MY_RUBY_HOME or JRUBY_HOME are not set' unless jruby_cpath

  puts 'Doing a simple compilation'
  sh %(javac -source 1.6 -target 1.6 -cp #{jruby_cpath}/lib/jruby.jar ext/java/**/*.java)
  mkdir_p 'lib/jrubytesting'
  sh %(jar cf lib/jrubytesting/test_jruby_library.jar -C ext/java jrubytesting/TestJrubyLibraryService.class)
  puts
end
task :default => :simple_compile
